miProyecto/about/urls.py
from django.urls import path
from .views import about

app_name = 'about'

urlpatterns = [
    path('', about, name='about'),
    
    
]

miProyecto/grafo/urls.py
from django.contrib import admin
from django.urls import path
from .views import grafos

app_name = "grafo"

urlpatterns = [
    path('',grafos, name="grafo")
]

miProyecto/home/urls.py
from django.contrib import admin
from django.urls import path
from .views import home, nohome

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    
]

miProyecto/miProyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from about import views
from sintactico import views
from grafo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('about.urls')),
    path('', include('sintactico.urls')),
    path('', include('grafo.urls')),
    
]

miProyecto/sintactico/urls.py
from django.contrib import admin
from django.urls import path
from .views import sintactico

app_name = 'sintactico'

urlpatterns = [
    path('', sintactico, name='sintactico'),
    

]

miProyecto/about/models.py
from django.db import models

# Create your models here.
class Body(models.Model):
    zones = models.CharField(max_length=50, blank=True,null=True)
    porcent = models.FloatField()
    tratamient = models.CharField(max_length=50, blank=True,null=True)


    class Meta:
        verbose_name = ("Cuerpo")
        verbose_name_plural = ("Cuerpos")
    
    def __str__(self):
        if self.name is not None:
            return str(self.zones) + self.tratamient
        else:
            return str(self.zones)

    def get_absolute_url(self):
        return reverse("Cuerpo_detail", kwargs={"pk": self.pk})

miProyecto/grafo/models.py
from django.db import models

# Create your models here.
class Grafos(models.Model):
    temperatura = models.FloatField()
    
    class Meta:
        verbose_name = ("Grafo")
        verbose_name_plural = ("Grafos")

    def __str__(self):
        if self.name is not None:
            return str(self.temperatura)
        else:
            return str(self.temperatura)

    def get_absolute_url(self):
        return reverse("Grafo_detail", kwargs={"pk": self.pk})

miProyecto/home/models.py
from django.db import models

# Create your models here.
class Pacientes(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = ("Paciente")
        verbose_name_plural = ("Pacientes")

    def __str__(self):
        return str(self.name)
    
    def get_absolute_url(self):
        return reverse("Paciente_detail", kwargs={"pk": self.pk})

''
class Tessiu(models.Model):
    temperatura = models.FloatField()
    color = models.FloatField()
    inflammation= models.FloatField(verbose_name="Inflamacion")
    name = models.ForeignKey(Pacientes, blank=True, null=True, verbose_name="nombre", on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = ("Tejido")
        verbose_name_plural = ("Tejidos")

    def __str__(self):
        if self.name is not None:
            return str(self.temperatura)
        else:
            return str(self.temperatura)

    def get_absolute_url(self):
        return reverse("Tejido_detail", kwargs={"pk": self.pk})

miProyecto/sintactico/models.py
from django.db import models

# Create your models here.
class Intern(models.Model):
    namePa = models.CharField(max_length=50, blank=True,null=True)
    age = models.FloatField()
    date = models.CharField(max_length=50, blank=True,null=True)

    class Meta:
        verbose_name = ("Interno")
        verbose_name_plural = ("Internos")

    def __str__(self):
        if self.name is not None:
            return str(self.namePa) + self.date
        else:
            return str(self.namePa)

    def get_absolute_url(self):
        return reverse("Interno_detail", kwargs={"pk": self.pk})

miProyecto/about/views.py
from django.http.response import HttpResponse
from django.shortcuts import render

# Create your views here.
def about(request):
    template_name="about/about.html"
    lista=[1,2,3,4,5]

    return render(request, template_name, {'miLista':lista})



        

miProyecto/grafo/views.py
from django.http.response import HttpResponse
from django.shortcuts import render


# Create your views here.
def grafos(request):
    tejidos=[1,2,3,4,5]
    resultado=extraeGrafo(tejidos)
    template_name="home/index.html"    

    diccionario={"resultado:":resultado}
    return render(request, template_name, diccionario)

def extraeGrafo(t):
    return

miProyecto/home/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from .models import Tessiu

# Create your views here.
def home(request):
    tejidos=Tessiu.objects.get_queryset()
    resultado=mifuncion(tejidos)
    template_name="home/index.html"    

    diccionario={'lista':tejidos, "resultado:":resultado}
    return render(request, template_name, diccionario)

def mifuncion(L):
    
    #df=np.array([[j,2:5]])
    #lista2=[{'r1':j,'r2':i,'conectado':'si'
    #        if abs(df.iloc[j,2:5]-df.iloc[i,2:5]).sum()<5
    #        else 'no'}
    #       for j in range(0,4)
    #       for i in range(j+1,5)]


    return "Hola"

def nohome(request):
    print("Saludos a la banda")
    template_name="home/index.html"
    return render(request, template_name, {})
    

def procesaLista(lista):
    #Hacer algo con la lista
    lista1=[]
    for elemento in lista:
        valor=elemento.temperatura**2 + elemento.inflammation**2 + elemento.color**2
        if valor > 50:
            lista1.append(valor**0.5)
    return lista1

miProyecto/sintactico/views.py
from django.http.response import HttpResponse
from django.shortcuts import render

# Create your views here.
def sintactico(request):
    template_name="sintactico/sintactico.html"
    return render(request, template_name, {})
    

miProyecto/about/templates/about/about.html
{% extends "index.html"%} {% block contenido%}

<h1> Pagina de About</h1>
<p>Nombre:{{nombre}} </p>
<p>Apellido: {{apellido}}</p>
<ul>

    {% for item in milista%}
    <li>
        {{item}}
    </li>
    {% endfor %}
</ul>
{% endblock contenido %}

miProyecto/grafo/templates/grafo.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grafo</title>
</head>

<body>

</body>

</html>

miProyecto/home/templates/home/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reconocimiento de Patrones</title>
</head>

<body>
    <div class="img-header">
        <h1>BIENVENIDO</h1>
        <hr>
        <p>Curso De Reconocimiento De Patrones Sintáctico Estructural</p>
    </div>
    <nav class="menu">
        <ul>
            <li><a href="{% url 'home:home' %}" target="_blank" class="activate">Home</a></li>
            <li><a href="{% url 'about:about' %}" target="_blank">About </a></li>
            <li><a href="{% url 'sintactico:sintactico' %}" target="_blank">Sintactico</a></li>
            <li><a href="{% url 'grafo:grafo' %}" target="_blank">Grafo </a></li>


        </ul>
    </nav>
    {% block contenido %}

    <h1>Cursito repasador para que Naruto aprenda</h1>
    <h2>Octubre mes del cancer de mama</h2>

    <table style="border: 1px black;">
        <thead>
            <tr>
                <th>Clave</th>
                <th>Temperatura</th>
                <th>Color</th>
                <th>Inflamacion</th>
            </tr>
        </thead>
        <tbody>
            {% for elemento in lista %}
            <tr>
                <th>{{elemento.pk}}</th>
                <th>{{elemento.temperatura}}</th>
                <th>{{elemento.color}}</th>
                <th>{{elemento.inflammation}}</th>
            </tr>
            {% endfor %}

        </tbody>

    </table>

    {% endblock contenido %}

</body>

</html>

miProyecto/sintactico/templates/sintactico/sintactico.html
{% extends "home/index.html"%} {% block contenido %}
<h1>La bandita rebelde</h1>

<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Excepturi illo amet vitae tempora suscipit optio molestiae consequuntur ea architecto obcaecati. Vitae numquam molestiae, explicabo dicta a maiores culpa fugit doloremque?

    <img src="https://www.google.com/url?sa=i&url=https%3A%2F%2Fas.com%2Fmeristation%2F2020%2F12%2F28%2Fnoticias%2F1609147235_045874.html&psig=AOvVaw0OxALM964jSnR_9RtKDk46&ust=1634960860677000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCPiIt_2N3fMCFQAAAAAdAAAAABAD"
        alt=""> {% endblock contenido %}
</p>